landscapeName: graphql
landscapeMemberClasses: []
# project: a092M00001G4R8CQAV # GraphQL Foundation
landscapeMemberCategory: Paima Engine Professionals
landscapefile: landscape.yml
# defaultCrunchbase: https://www.crunchbase.com/organization/graphql-foundation
missingcsvfile: missing.csv
memberSuffix: " (member)"