global:
  name: GraphQL Landscape
  short_name: GraphQL
  repo: graphql/graphql-landscape
  website: https://landscape.paimastudios.com
  short_domain: l.paimastudios.com
  company_url: https://paimastudios.com
  email: contact@paimastudios.com
  meta:
    title: Paima Landscape
    description: Filter and sort by GitHub stars, funding, commits, contributors, hq location, and tweets
    twitter: "@PaimaStudios"
  membership: Unused
  flags:
    hide_license_for_categories:
      - Paima Engine Professionals
      - Ecosystem Partners
      - Unused
twitter:
  search: landscape.paimastudios.com
  url: https://landscape.paimastudios.com
  text: Paima Landscape
relation:
  label: Paima Relation
  url: graphql
  values:
    - id: hosted
      label: Unused filter
      children:
        - id: foundationproject
          label: Unused filter
          prefix: GraphQL
          tag: Foundation Project
          color: "#3570af"
          big_picture_order: 1
          big_picture_label: GraphQL Foundation Project
          big_picture_color: rgb(24,54,114)
    - id: company
      label: Unused filter
      tag: Company
      big_picture_order: 3
    - id: member
      label: Unused filter
      tag: Ecosystem Partners
    - id: false
      label: Unused filter
      url: "no"
membership: []
home:
  header: >
    <h1>Paima Landscape</h1> The Paima landscape (<a target="_blank" href="images/landscape.png">png</a>, <a target="_blank"
    href="images/landscape.pdf">pdf</a>) is dynamically generated below. It is modeled after the <a href="http://landscape.cncf.io">CNCF landscape</a> and based
    on the same open source code.
  footer: |
    Crunchbase data is used under license from Crunchbase to CNCF.
presets:
  - url: /format=card-mode&grouping=no&license=open-source&sort=first-commit
    label: Open source cards by age
  - url: /license=apache-license-2-0
    label: Apache-2.0 landscape
  - url: /format=card-mode&grouping=category
    label: Cards in categories
  - url: /format=card-mode&grouping=no&sort=stars
    label: Cards by stars
  - url: /format=card-mode&grouping=headquarters
    label: Group by location
  - url: /format=card-mode&grouping=no&sort=amount
    label: Cards by MCap/Funding
big_picture:
  main:
    tab_index: -1
    url: landscape
    name: Landscape
    title: Paima Landscape
    fullscreen_header: See the interactive landscape at l.paimastudios.com
    elements:
      - type: HorizontalCategory
        category: Projects
        rows: 4
        width: 970
        height: 160
        top: 0
        left: 0
        color: rgb(4,81,49)
        fit_width: true
        is_large: true
      - type: HorizontalCategory
        category: Paima Engine Professionals
        rows: 6
        width: 970
        height: 195
        top: 180
        left: 0
        color: rgb(126,115,14)
        fit_width: true
        is_large: true
      - type: HorizontalCategory
        category: Ecosystem Partners
        rows: 4
        width: 650
        height: 150
        top: 390
        left: 0
        color: rgb(103,66,18)
        fit_width: true
        is_large: true
      - type: LandscapeInfo
        width: 310
        height: 150
        top: 390
        left: 665
        children:
          - type: text
            text: |
              This landscape is intended as a map to explore the Paima ecosystem
            top: 45
            left: 140
            right: 10
            font_size: 10
          - type: image
            image: qr.svg
            top: 10
            left: 20
            width: 90
            height: 90
            title: QR Code
          - type: title
            title: paimastudios.com
            top: 95
            left: 10
            font_size: 21
          - type: image
            image: right-logo.svg
            width: 90
            right: 10
            top: 10
            title: Paima Logo
test:
  header: Paima Landscape
  section: Paima Engine Professionals
  logo: twitter.svg
